// packages/react/src/PivotTable.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import type { CSSProperties } from 'react';
import { PivotTable as WebPivotTable, type PivotTableOptions } from '@pvotly/web';
import type {
  ExportFormat,
  ExportOptions,
  ThemeName,
  ThemeTokens,
  ActionBarConfig,
} from '@pvotly/web';
import type {
  PivotConfiguration,
  PivotEngine,
  PivotEventMap,
} from '@pvotly/core';

type EventHandlers = {
  onReady?: () => void;
  onReportChange?: (config: PivotEventMap['reportChange']) => void;
  onDataChange?: (payload: PivotEventMap['dataChange']) => void;
  onCellClick?: (payload: PivotEventMap['cellClick']) => void;
  onCellDoubleClick?: (payload: PivotEventMap['cellDoubleClick']) => void;
  onFilterChange?: (payload: PivotEventMap['filterChange']) => void;
  onSortChange?: (payload: PivotEventMap['sortChange']) => void;
  onDrillThrough?: (payload: PivotEventMap['drillThrough']) => void;
  onError?: (payload: PivotEventMap['error']) => void;
};

export interface PivotTableProps extends PivotTableOptions, EventHandlers {
  className?: string;
  style?: CSSProperties;
}

export interface PivotTableHandle {
  /** The underlying engine for imperative control. */
  readonly engine: PivotEngine;
  /** The underlying web widget instance. */
  readonly instance: WebPivotTable;
  getConfiguration(): PivotConfiguration;
  setConfiguration(config: PivotConfiguration): void;
  setTheme(theme: ThemeName): void;
  setTokens(tokens: ThemeTokens): void;
  setActionBar(config: ActionBarConfig): void;
  openFieldsDialog(): void;
  openFormatDialog(): void;
  openConditionalDialog(): void;
  openFilterDialog(uniqueName: string): void;
  exportTo(format: ExportFormat, options?: ExportOptions): void;
  print(title?: string): void;
  refresh(): void;
}

const EVENT_MAP: Array<[keyof EventHandlers, keyof PivotEventMap]> = [
  ['onReady', 'ready'],
  ['onReportChange', 'reportChange'],
  ['onDataChange', 'dataChange'],
  ['onCellClick', 'cellClick'],
  ['onCellDoubleClick', 'cellDoubleClick'],
  ['onFilterChange', 'filterChange'],
  ['onSortChange', 'sortChange'],
  ['onDrillThrough', 'drillThrough'],
  ['onError', 'error'],
];

function pivotConfigurationFromProps(props: PivotTableProps): PivotConfiguration {
  return {
    dataSource: props.dataSource,
    slice: props.slice,
    options: props.options,
    formats: props.formats,
    conditions: props.conditions,
    localization: props.localization,
    valuesAxis: props.valuesAxis,
    customAggregators: props.customAggregators,
    locale: props.locale,
    serverSide: props.serverSide,
  };
}

function configKey(props: PivotTableProps): string {
  return JSON.stringify(pivotConfigurationFromProps(props), (_k, v) =>
    typeof v === 'function' ? '[fn]' : v,
  );
}

/**
 * Declarative React wrapper around the `@pvotly/web` widget.
 *
 * @example
 * ```tsx
 * <PivotTable
 *   dataSource={{ data }}
 *   slice={{ rows: [{ uniqueName: 'Country' }], measures: [{ uniqueName: 'Sales' }] }}
 *   onCellClick={({ cell }) => console.log(cell)}
 * />
 * ```
 */
export const PivotTable = forwardRef<PivotTableHandle, PivotTableProps>(function PivotTable(
  props,
  ref,
) {
  const hostRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<WebPivotTable | null>(null);
  const handlersRef = useRef<EventHandlers>(props);
  handlersRef.current = props;

  // Create the widget once on mount.
  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    // Strip React-only props (className/style) and the event-handler props so
    // only the serializable PivotConfiguration + UI options reach the widget
    // (the engine deep-clones its config and would choke on function values).
    const {
      className: _c,
      style: _s,
      onReady: _onReady,
      onReportChange: _onReportChange,
      onDataChange: _onDataChange,
      onCellClick: _onCellClick,
      onCellDoubleClick: _onCellDoubleClick,
      onFilterChange: _onFilterChange,
      onSortChange: _onSortChange,
      onDrillThrough: _onDrillThrough,
      onError: _onError,
      ...options
    } = props;
    const instance = new WebPivotTable(host, options as PivotTableOptions);
    instanceRef.current = instance;

    // Bridge events to the latest prop handlers (kept in a ref).
    const unsubs = EVENT_MAP.map(([propName, eventName]) =>
      instance.on(eventName as 'cellClick', ((payload: unknown) => {
        const handler = handlersRef.current[propName] as ((p: unknown) => void) | undefined;
        handler?.(payload);
      }) as never),
    );

    return () => {
      unsubs.forEach((u) => u());
      instance.destroy();
      instanceRef.current = null;
    };
  }, []);

  // Push config changes into the widget.
  const key = configKey(props);
  useEffect(() => {
    const instance = instanceRef.current;
    if (!instance) return;
    instance.setConfiguration(pivotConfigurationFromProps(props));
  }, [key]);

  // Theme updates without a full reset.
  useEffect(() => {
    if (props.theme) instanceRef.current?.setTheme(props.theme);
  }, [props.theme]);

  // Style tokens (the `tokens` prop) applied reactively.
  const tokensKey = JSON.stringify(props.tokens ?? null);
  useEffect(() => {
    if (props.tokens) instanceRef.current?.setTokens(props.tokens);
  }, [tokensKey]);

  // Action-bar config applied reactively (functions compared by presence only).
  const actionBarKey = JSON.stringify(props.actionBar ?? null, (_k, v) =>
    typeof v === 'function' ? '[fn]' : v,
  );
  useEffect(() => {
    if (props.actionBar) instanceRef.current?.setActionBar(props.actionBar);
  }, [actionBarKey]);

  useImperativeHandle(
    ref,
    (): PivotTableHandle => {
      return {
        get engine() {
          return instanceRef.current!.engine;
        },
        get instance() {
          return instanceRef.current!;
        },
        getConfiguration: () => instanceRef.current!.getConfiguration(),
        setConfiguration: (config) => instanceRef.current!.setConfiguration(config),
        setTheme: (theme) => instanceRef.current!.setTheme(theme),
        setTokens: (tokens) => instanceRef.current!.setTokens(tokens),
        setActionBar: (config) => instanceRef.current!.setActionBar(config),
        openFieldsDialog: () => instanceRef.current!.openFieldsDialog(),
        openFormatDialog: () => instanceRef.current!.openFormatDialog(),
        openConditionalDialog: () => instanceRef.current!.openConditionalDialog(),
        openFilterDialog: (uniqueName) => instanceRef.current!.openFilterDialog(uniqueName),
        exportTo: (format, options) => instanceRef.current!.exportTo(format, options),
        print: (title) => instanceRef.current!.print(title),
        refresh: () => instanceRef.current!.refresh(),
      };
    },
    [],
  );

  return <div ref={hostRef} className={props.className} style={props.style} />;
});

// packages/angular/src/pivot-table.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  type AfterViewInit,
  type OnChanges,
  type OnDestroy,
  type SimpleChanges,
} from '@angular/core';
import {
  PivotTable as WebPivotTable,
  type PivotTableOptions,
  type ActionBarConfig,
  type ThemeName,
  type ThemeTokens,
  type ExportFormat,
  type ExportOptions,
} from '@pvotly/web';
import type {
  ConditionalFormat,
  DataRecord,
  DataSourceConfig,
  FieldFilter,
  Localization,
  NumberFormat,
  PivotCell,
  PivotConfiguration,
  PivotEngine,
  PivotEventMap,
  PivotOptions,
  Slice,
  SortDirection,
} from '@pvotly/core';

/**
 * Standalone Angular component wrapping the framework-agnostic `@pvotly/web`
 * widget.
 *
 * Remember to import the stylesheet once in your app (e.g. in `angular.json`
 * `styles` or a global stylesheet):
 *
 * ```ts
 * import '@pvotly/web/styles.css';
 * ```
 *
 * @example
 * ```html
 * <pvotly-table
 *   [dataSource]="{ data }"
 *   [slice]="{ rows: [{ uniqueName: 'Country' }], measures: [{ uniqueName: 'Sales' }] }"
 *   (cellClick)="onCellClick($event)"
 * ></pvotly-table>
 * ```
 */
@Component({
  selector: 'pvotly-table',
  standalone: true,
  template: '<div #host></div>',
})
export class PivotTableComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** Host element the widget renders into. */
  @ViewChild('host', { static: true }) hostRef!: ElementRef<HTMLElement>;

  /* ---- PivotConfiguration inputs ------------------------------------- */

  /** Data source (records, fields, etc.). */
  @Input() dataSource!: DataSourceConfig;
  /** Rows / columns / measures slice. */
  @Input() slice?: Slice;
  /** Engine options (totals, drill-through, etc.). */
  @Input() options?: PivotOptions;
  /** Number-format definitions. */
  @Input() formats?: NumberFormat[];
  /** Conditional-formatting rules. */
  @Input() conditions?: ConditionalFormat[];
  /** Localization strings. */
  @Input() localization?: Localization;

  /* ---- Widget UI inputs ---------------------------------------------- */

  /** Show the toolbar (default true). */
  @Input() toolbar?: boolean;
  /** Show the drag-and-drop field-list panel (default true). */
  @Input() fieldList?: boolean;
  /** Theme name (default 'light'). */
  @Input() theme?: ThemeName;
  /** Typed style tokens applied as CSS variables. */
  @Input() tokens?: ThemeTokens;
  /** Action-bar configuration. */
  @Input() actionBar?: ActionBarConfig;
  /** CSS height for the widget (e.g. 500 or '60vh'). */
  @Input() height?: string | number;
  /** CSS width. */
  @Input() width?: string | number;

  /* ---- Events -------------------------------------------------------- */

  @Output() ready = new EventEmitter<PivotEventMap['ready']>();
  @Output() reportChange = new EventEmitter<PivotEventMap['reportChange']>();
  @Output() dataChange = new EventEmitter<PivotEventMap['dataChange']>();
  @Output() cellClick = new EventEmitter<PivotEventMap['cellClick']>();
  @Output() cellDoubleClick = new EventEmitter<PivotEventMap['cellDoubleClick']>();
  @Output() filterChange = new EventEmitter<PivotEventMap['filterChange']>();
  @Output() sortChange = new EventEmitter<PivotEventMap['sortChange']>();
  @Output() drillThrough = new EventEmitter<PivotEventMap['drillThrough']>();
  @Output() error = new EventEmitter<PivotEventMap['error']>();

  private instance: WebPivotTable | null = null;
  private unsubs: Array<() => void> = [];

  /** The underlying engine for imperative control (available after init). */
  get engine(): PivotEngine | undefined {
    return this.instance?.engine;
  }

  /** The underlying web widget instance (available after init). */
  get widget(): WebPivotTable | null {
    return this.instance;
  }

  ngAfterViewInit(): void {
    const host = this.hostRef.nativeElement;
    this.instance = new WebPivotTable(host, this.buildOptions());

    const map: Array<[keyof PivotEventMap, EventEmitter<unknown>]> = [
      ['ready', this.ready as EventEmitter<unknown>],
      ['reportChange', this.reportChange as EventEmitter<unknown>],
      ['dataChange', this.dataChange as EventEmitter<unknown>],
      ['cellClick', this.cellClick as EventEmitter<unknown>],
      ['cellDoubleClick', this.cellDoubleClick as EventEmitter<unknown>],
      ['filterChange', this.filterChange as EventEmitter<unknown>],
      ['sortChange', this.sortChange as EventEmitter<unknown>],
      ['drillThrough', this.drillThrough as EventEmitter<unknown>],
      ['error', this.error as EventEmitter<unknown>],
    ];
    this.unsubs = map.map(([event, emitter]) =>
      this.instance!.on(event as 'cellClick', ((payload: unknown) =>
        emitter.emit(payload)) as never),
    );
  }

  ngOnChanges(changes: SimpleChanges): void {
    const instance = this.instance;
    // Before init the constructor picks everything up; nothing to push.
    if (!instance) return;

    const configKeys = ['dataSource', 'slice', 'options', 'formats', 'conditions', 'localization'];
    if (configKeys.some((k) => k in changes)) {
      instance.setConfiguration(this.buildConfiguration());
    }
    if ('theme' in changes && this.theme) instance.setTheme(this.theme);
    if ('tokens' in changes && this.tokens) instance.setTokens(this.tokens);
    if ('actionBar' in changes && this.actionBar) instance.setActionBar(this.actionBar);
  }

  ngOnDestroy(): void {
    this.unsubs.forEach((u) => u());
    this.unsubs = [];
    this.instance?.destroy();
    this.instance = null;
  }

  /* ---- Imperative API ------------------------------------------------ */

  getConfiguration(): PivotConfiguration | undefined {
    return this.instance?.getConfiguration();
  }

  setConfiguration(config: PivotConfiguration): void {
    this.instance?.setConfiguration(config);
  }

  /** Apply typed style tokens reactively. */
  setTokens(tokens: ThemeTokens): void {
    this.instance?.setTokens(tokens);
  }

  /** Update the action-bar configuration. */
  setActionBar(config: ActionBarConfig): void {
    this.instance?.setActionBar(config);
  }

  /** Switch the theme without a full reset. */
  setTheme(theme: ThemeName): void {
    this.instance?.setTheme(theme);
  }

  openFieldsDialog(): void {
    this.instance?.openFieldsDialog();
  }

  openFormatDialog(): void {
    this.instance?.openFormatDialog();
  }

  openConditionalDialog(): void {
    this.instance?.openConditionalDialog();
  }

  openFilterDialog(uniqueName: string): void {
    this.instance?.openFilterDialog(uniqueName);
  }

  exportTo(format: ExportFormat, options?: ExportOptions): void {
    this.instance?.exportTo(format, options);
  }

  print(title?: string): void {
    this.instance?.print(title);
  }

  refresh(): void {
    this.instance?.refresh();
  }

  /* ---- internals ----------------------------------------------------- */

  private buildConfiguration(): PivotConfiguration {
    return {
      dataSource: this.dataSource,
      slice: this.slice,
      options: this.options,
      formats: this.formats,
      conditions: this.conditions,
      localization: this.localization,
    };
  }

  private buildOptions(): PivotTableOptions {
    const opts: PivotTableOptions = { ...this.buildConfiguration() };
    if (this.toolbar !== undefined) opts.toolbar = this.toolbar;
    if (this.fieldList !== undefined) opts.fieldList = this.fieldList;
    if (this.theme !== undefined) opts.theme = this.theme;
    if (this.tokens !== undefined) opts.tokens = this.tokens;
    if (this.actionBar !== undefined) opts.actionBar = this.actionBar;
    if (this.height !== undefined) opts.height = this.height;
    if (this.width !== undefined) opts.width = this.width;
    return opts;
  }
}

// Re-export the payload helper types so consumers can type their handlers.
export type {
  PivotCell,
  DataRecord,
  FieldFilter,
  SortDirection,
};
